### ISSUE TITLE
THANK YOU FOR BRINGING OLD PRODIGY BACK!

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#1]
the 2017 one brings back memories and omg thanks alot and make sure it does not get dmca!

**Comment by Daboss7173** [comment]
I made sure it wouldn't via good ol' loopholes :D

**Comment by XPMUser** [comment]
I'm not a pirate

**Comment by XPMUser** [comment]
We are not pirates

**Comment by XPMUser** [comment]
Imagine seeing this 
![Screenshot 2023-04-29 203218](https://user-images.githubusercontent.com/109283781/235329819-d69449c4-8696-4198-a49a-67906223d03f.png)
