### ISSUE TITLE
There is no way to go home in version 1.11.0.

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#10]
In 2015, there was a way to go home in version 1.11.0 using prodigygame.com but now the house feature is missing in slappygig.github.io when using version 1.11.0.

**Comment by XPMUser** [comment]
Unless I reuse saved file

**Comment by XPMUser** [comment]
I have a problem with the house in version 1.11.0 only.

**Comment by Daboss7173** [comment]
That's because the house didn't exist in 1.11.0
Not a bug.

**Comment by XPMUser** [comment]
I knew Prodigy Math Man had a chance

**Comment by XPMUser** [comment]
> That's because the house didn't exist in 1.11.0 Not a bug.

[https://www.youtube.com/@prodigymathman8501](url)

You didn't know the codes to make going home available in this version.

**Comment by XPMUser** [comment]
This topic is in your DM
