### ISSUE TITLE
Prodigy Definitive Edition doesn't boot up in Internet Explorer.

### ISSUE THREAD

**Issue by Ao28th28** [Daboss7173/Daboss7173.github.io#105]
What went wrong:
Prodigy Definitive Edition doesn't work in Internet Explorer.
How can I replicate this:
Unknown
Console log output:
None

![VirtualBox_Windows 7_25_01_2024_18_24_20](https://github.com/Daboss7173/Daboss7173.github.io/assets/122099346/a840602f-01e6-4e9b-acbc-1a6183d29b55)
![Capture](https://github.com/Daboss7173/Daboss7173.github.io/assets/122099346/59e38e82-0354-4786-beb9-2ee223d38ed6)

**Comment by Daboss7173** [comment]
This isn't a bug. Internet Explorer is an outdated (and insecure) browser, and is not supported by most modern websites, including this one.
