### ISSUE TITLE
March 2015's Clockwork Town (Tech Zone) in your Definitive Edition

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#123]
What would you like to add: 
March 2015's Clockwork Town (Tech Zone) in your Definitive Edition
How would you want it to be implemented:
Add this zone so that I can get the Techeater name.
Any additional context:
I've never changed my name to Techeater before.

**Comment by Daboss7173** [comment]
Clockwork Town is already in definitive edition, adding it again would be redundant.

**Comment by XPMUser** [comment]
> Clockwork Town is already in definitive edition, adding it again would be redundant.

I mean 1.10.0 not 1.11.0 or later.
