### ISSUE TITLE
In the Tree in your Definitive Edition

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#124]
What would you like to add: 
In the Tree in your Definitive Edition
How would you want it to be implemented:
Use anything as placeholders to fix parts of In the Tree.
Any additional context:
Use my 1.8.9's tileset-tree files.

**Comment by Daboss7173** [comment]
Not really the best idea out there.

Not only is it an unused zone without any trace of the original assets left over. When a project is named "Definitive Edition", that implies quality > quantity. Adding this zone is NOT that.
