### ISSUE TITLE
Reduce the amount of items needed to complete the packrat achievement.

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#126]
What would you like to change: 
Reduce the number of items from 50 to 30.
How would you want it to be implemented:
Make that change so I could complete that achievement.
Any additional context:
I'm unable to get 50 different collectable items.

**Comment by Daboss7173** [comment]
I added more item drops a little over a week ago so the achievement is possible now (and i've completed it)
