### ISSUE TITLE
The Save Battle Feature

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#127]
What would you like to add: 
The Save Battle Feature
How would you want it to be implemented:
Install this feature so that I don't have to start over in the Epics Subspace.
Any additional context:
It's like saving games in Windows Vista/7 games and Plants Vs. Zombies. In Plants Vs. Zombies, if you save your level data, you can continue it later.

**Comment by Daboss7173** [comment]
A battle isn't a level in a game, and doing all of the battles in a streak is kind of the point of it all.
