### ISSUE TITLE
Replace late 2015 and later's Bok & Slip with 2014-2015's Bok & Slip

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#128]
What would you like to add: 
2014-2015's Bok & Slip in 2014-2015's Shiverchill Mountains.
How would you want it to be implemented:
Use Paint 3D, Paint, and/or Texture Packer
Any additional context:
Using late 2015 and later's Bok & Slip doesn't make the sprites or faces vanilla, I would consider it a placeholder.

**Comment by Daboss7173** [comment]
While this is possible in theory, it will not work in practice. The original sprites just don't exist anymore, and using super compressed sprites from YouTube videos would be super jarring, and super low quality compared to the rest of the game.
