### ISSUE TITLE
Bannard

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#13]
Battling Bannard froze the game

**Comment by Daboss7173** [comment]
> ###
> **[XPMUser](/XPMUser) ** commented [Apr 28, 2023](#issue-1689156195) •
Sorry but I need more info. Which version are you talking about?

**Comment by Daboss7173** [comment]
> Battling Bannard froze the game

Sorry, but I need more info, which version are you talking about?

**Comment by XPMUser** [comment]
How about we play a game called guess the version?

**Comment by XPMUser** [comment]
Bannard's body except for the head is invisible.

**Comment by Daboss7173** [comment]
> How about we play a game called guess the version?

Yeah, funny story their head isn't invisible for me in any of the versions, I've tested all of them. If you don't just tell me I'll have to close this.

**Comment by XPMUser** [comment]
The guessing game has been paused. I will close it myself.

**Comment by XPMUser** [comment]
GAME OVER

**Comment by XPMUser** [comment]
Lost Game

I won

**Comment by XPMUser** [comment]
Bannard is broken in slappygig.github.io so never mind.
