### ISSUE TITLE
A mod with Prodigy's api available

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#131]
What would you like to add: 
A mod with Prodigy's api available
How would you want it to be implemented:
Use their file directory and Time travel to the past to get the missing api files.
Any additional context:
I miss the older versions of Multiplayer Mode.

**Comment by Daboss7173** [comment]
Yeah, I hate to break it to you, but time travel is science fiction. Sorry dude.
