### ISSUE TITLE
Cant save character 

### ISSUE THREAD

**Issue by Toonigy** [Daboss7173/Daboss7173.github.io#132]
What went wrong: 
i am using Xbox one and i know the edge app does not support file downloading, i tried web browsers that support downloads, the load character works but when i click save character it won't download my save so can you add google login, accounts or something 
How can I replicate this:

Console log output:

**Comment by Daboss7173** [comment]
It probably won't let you do that either, it's pretty closed off.

Plus this isn't a bug, it's just an unsupported browser.
