### ISSUE TITLE
Add 3-0-0 and 2-0-0 versions 

### ISSUE THREAD

**Issue by Toonigy** [Daboss7173/Daboss7173.github.io#134]
What would you like to add:  
Version 2-0-0 and 3-0-0

**Comment by Daboss7173** [comment]
I'll probably add 3-0-0 eventually, but it's not where my priorities are. There's a lot of other versions to cover first, I wanna do those as well as get some more definitive edition updates out before then.

As for 2-0-0, I probably won't add it as there's not really much that makes it stand out from the other versions. It's essentially just a discount 1-90-0. If I do add this, it'll probably be a long time from now.
