### ISSUE TITLE
Healstones in a zone with the key called 'Tower' where you click on the orb to do battles after the wheel spins in your Definitive Edition.

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#139]
### What would you like to add?

Healstones in a zone with the key called 'Tower' where you click on the orb to do battles after the wheel spins.

### How would you like this to be implemented? (optional)

Add the healstone in case I run out of food.

### Any additional context (optional)

I'm tired of wasting 100 gold and/or being stuck on any unpassable floor.

**Comment by Daboss7173** [comment]
Yeah, not doing this. That would ruin the point of the whole thing.

**Comment by XPMUser** [comment]
I've seen players that were stuck on floor 79 before.

**Comment by XPMUser** [comment]
This can make reaching floor 100 without spending 500 gold possible.

**Comment by XPMUser** [comment]
![Screenshot 2024-05-29 183948](https://github.com/Daboss7173/Daboss7173.github.io/assets/109283781/c3ea96c6-ecf2-40c4-8001-47ff03aa2cef)

**Comment by XPMUser** [comment]
This is the only most possible way to complete the Dark Tower in 1 go.
