### ISSUE TITLE
Version 1.17.0

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#14]
The map only shows that firefly forest and the house are available.

**Comment by XPMUser** [comment]
How to go to Barnacle Cove in this version?

**Comment by Daboss7173** [comment]
The maps are gone to by clicking the upside-down pyramid icons above the area they correspond with.
Not a bug.

**Comment by XPMUser** [comment]
THIS IS BECAUSE I DIDN'T COMPLETE THE TUTORIAL IN THIS VERSION

**Comment by XPMUser** [comment]
> The maps are gone to by clicking the upside-down pyramid icons above the area they correspond with. Not a bug.

MOTS: Complete the tutorial in version 1.17.0
