### ISSUE TITLE
Market and Peddler's Corner in your Definitive Edition

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#140]
### What went wrong?

Market and/or Peddler's Corner can't boot up after a while of not going to either of them. Refreshing the page solves the problem, but this problem didn't occur in my 1.50.0 Definitive Edition, Ultimate Edition, or Prodidows for the Market even without refreshing the page.

### How can I reproduce this?

Use a different source like Daboss7173.github.io.

### What did the console output?
![Screenshot 2024-06-06 183046](https://github.com/Daboss7173/Daboss7173.github.io/assets/109283781/bce6eba9-0bc7-40a6-a3bd-29e361c50df7)

I missed the Peddler's Corner console log. When it comes back, I'll put it here.

**Comment by Daboss7173** [comment]
Yeah, that's a bug with how Byethost serves files, not with Definitive Edition. Sorry.
