### ISSUE TITLE
Prodigy Definitive Edition Dashboard for Parents and Teachers

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#143]
### What would you like to add?

Prodigy Definitive Edition Dashboard for Parents and Teachers

### How would you like this to be implemented? (optional)

Add it so that the following happens since you have math installed:
1. Parents can send in-game cheers, set rewards and learning goals, help their children with their homework, and get notified about their kids' progress.
2. Teachers can give students classwork and homework, help them with their classwork, and give their children class codes.

### Any additional context (optional)

This will help students get their math work, quizzes, exams, etc done.

**Comment by XPMUser** [comment]
If Math affects the Don't Stop Me Now achievement, you can add it back.

**Comment by XPMUser** [comment]
Can you also add an enforce option so that parents and or teachers can prevent students/kids from turning math off until their math homework is finished?

**Comment by Daboss7173** [comment]
The math system is not designed for classes or anything like that - It's just for fun! An optional challenge for those who want it.
Basically this dashboard thing wouldn't work with this. I'm not trying to replace the actual game with this. I'm just opening a window into the past.

**Comment by Daboss7173** [comment]
The questions are randomized. There's no placement test, or any tests of any kind. Just questions.
