### ISSUE TITLE
Ice Dragon Tooth Crown in your Definitive Edition

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#148]
### What would you like to add?

Ice Dragon Tooth Crown in your Definitive Edition

### How would you like this to be implemented? (optional)

Use any software like Paint.net, Paint, Paint 3D, etc to change the color of the Dragon Spike Crown to the same color the Ice Dragon Tooth Crown to make it. Add it in case some people don't get The Master of Trials, but they don't like losing hearts after a battles with monsters that have at least 200 health.

### Any additional context (optional)

The Ice Dragon Tooth Crown used to have Damage Bonuses.

**Comment by Daboss7173** [comment]
This has been added to the game.
