### ISSUE TITLE
I'm still stuck with Starter Home in the open source version of 1.50.0.

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#149]
### What went wrong?

I can't move to a different house in your open source version of 1.50.0.

### How can I reproduce this?

Try moving to a different house in your open source version of 1.50.0.

### What did the console output?

I saw nothing logged, but I'm still unable to move to a different house.

**Comment by XPMUser** [comment]
I wasn't stuck with Starter Home back in 2017 on the original Prodigy site.

**Comment by Daboss7173** [comment]
This is fixed now. Thanks for reporting!
