### ISSUE TITLE
Player Card not showing

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#15]
Player Card is not showing when clicking on the wizard in versions before Shiverchill Mountains changed.

**Comment by Daboss7173** [comment]
The player card wasn't implimented in the same way as the later versions. The leftward-most hud button (the book that says menu) was essentially what replaced the player card in the earlier versions.
Not a bug.

**Comment by XPMUser** [comment]
I remember a video otherwise like a dream of the opposite

**Comment by XPMUser** [comment]
CAMDEN BELL'S 1st VIDEO
