### ISSUE TITLE
Google Sign-In mod

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#150]
### What would you like to add?

The Google Sign-In mod

### How would you like this to be implemented? (optional)

Add it so that I can get my saves from open source versions linked to my Google account.

### Any additional context (optional)

This can help me not worry about finding save files and in case people are tired of saving manually.

**Comment by XPMUser** [comment]
I saw the Google Sign-In feature back in 2017 on the original Prodigy site and Prodigy Education didn't use your Definitive Edition.

**Comment by XPMUser** [comment]
Sometimes some iPad users want to play older open source versions without starting over.

**Comment by Daboss7173** [comment]
Sorry, but it just wouldn't be feasible with the current system -- especially as a modpack.
