### ISSUE TITLE
Add the missing arm for the reduced male version of Mira's Robes in your Definitive Edition.

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#151]
### What would you like to add?

The missing arm for the reduced male version of Mira's Robes in your Definitive Edition.

### How would you like this to be implemented? (optional)

I've managed to do it in some of my versions, but the arm is shaking. In order to fix the shaking problem, try guessing the numbers, use Texture Packer, etc.

### Any additional context (optional)

I found a video back in 2017 about the arm being behind the wizard's back, but I didn't even see the shoulder. The video about it is no longer available.

**Comment by XPMUser** [comment]
![Capture](https://github.com/user-attachments/assets/100f5904-88d2-4c15-9c36-d18b7371c49e)

**Comment by Daboss7173** [comment]
This was fixed in the latest release of Definitive Edition.

Thanks for reporting.
