### ISSUE TITLE
Mira's Robes reduced male arm mod

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#152]
### What would you like to add?

The missing arm for the reduced male version of Mira's Robes.

### How would you like this to be implemented? (optional)

Add it as a modpack for 2015-2017's versions.

**Comment by Daboss7173** [comment]
Well if I add something that is fundamentally more of a bug fix than a modpack, it'll arrive as a bug fix, not a modpack.
