### ISSUE TITLE
add more versions

### ISSUE THREAD

**Issue by Toonigy** [Daboss7173/Daboss7173.github.io#153]
### What would you like to add?

new versions

### How would you like this to be implemented? (optional)

add more versions to the site please

**Comment by Daboss7173** [comment]
As previously mentioned in your other  issue about adding new versions [here,](https://github.com/Daboss7173/Daboss7173.github.io/issues/145) I will be ignoring issues related to adding new versions for the reasons stated in the issue template.

I will add new versions, but not according to some grand schedule or something. Please stop making issues about this.

Thanks.
