### ISSUE TITLE
Login screen, save character button, etc for 3.15.3

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#154]
### What would you like to add?

Login screen, save character button, undone softlocks, etc for 3.15.3

### How would you like this to be implemented? (optional)

If you're able to understand the codes for 3.15.3's files, this should be possible. If you don't want to add the save character button in settings, can you at least add a Google Sign-in feature?

**Comment by Daboss7173** [comment]
> ### What would you like to add?
> Login screen, save character button, undone softlocks, etc for 3.15.3
> 
> ### How would you like this to be implemented? (optional)
> If you're able to understand the codes for 3.15.3's files, this should be possible. If you don't want to add the save character button in settings, can you at least add a Google Sign-in feature?

Saving and loading has been added in the most recent update.
