### ISSUE TITLE
Rune Run is no longer available

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#159]
### What went wrong?

Rune Run isn't available

### How can I reproduce this?

Try to do the Rune Run.

### What did the console output?

<html>
<body>
<div tabindex="-1" class="console-group console-group-messages" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; color: rgb(27, 27, 27); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div tabindex="-1" class="console-message-wrapper console-from-api console-info-level console-selected" jslog="Item; context: console-message; track: click, keydown: ArrowUp|ArrowDown|ArrowLeft|ArrowRight|Enter|Space|Home|End" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; display: flex; flex-direction: column; margin: 4px; border-radius: 5px; --console-color-black: #000; --console-color-red: #a00; --console-color-green: #0a0; --console-color-yellow: #a50; --console-color-blue: #00a; --console-color-magenta: #a0a; --console-color-cyan: #0aa; --console-color-gray: #aaa; --console-color-darkgray: #555; --console-color-lightred: #f55; --console-color-lightgreen: #5f5; --console-color-lightyellow: #ff5; --console-color-lightblue: #55f; --console-color-ightmagenta: #f5f; --console-color-lightcyan: #5ff; --console-color-white: #fff; background-color: var(--sys-color-tonal-container);"><div class="console-row-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; flex-direction: row;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start; margin-top: -1px;"><div class="console-message-stack-trace-wrapper" aria-label=" console.trace Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><button class="devtools-link text-button link-style" jslog="Link; track: click" role="link" tabindex="-1" title="https://daboss7173.github.io/oldprodigy/3-15-3/js/game.min.js:940" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font: inherit; margin: 0px; height: 18px; border: none; border-radius: 2px; padding: 0px !important; color: var(--sys-color-primary); background: none !important; flex: 0 0 auto; white-space: nowrap; text-decoration: underline; outline-offset: 2px; outline: none; cursor: pointer; max-width: 100%; overflow: hidden; text-overflow: ellipsis; word-break: break-all;"><br class="Apple-interchange-newline">game.min.js:940</button> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">console.trace</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace stack-preview-container width-constrained" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; width: 485px; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">
  | t.log | @ | game.min.js:940
-- | -- | -- | --
  | (anonymous) | @ | game.min.js:750
  | t.log | @ | game.min.js:749
  | (anonymous) | @ | game.min.js:3928
  | (anonymous) | @ | game.min.js:3758
  | (anonymous) | @ | game.min.js:3757
  | (anonymous) | @ | game.min.js:221
  | (anonymous) | @ | game.min.js:232
  | h | @ | game.min.js:137
  | Promise.then (async) |   |  
  | u | @ | game.min.js:152
  | h | @ | game.min.js:137
  | Promise.then (async) |   |  
  | u | @ | game.min.js:152
  | (anonymous) | @ | game.min.js:154
  | a | @ | game.min.js:134
  | t.sendFetchRequest | @ | game.min.js:3731
  | (anonymous) | @ | game.min.js:3714
  | (anonymous) | @ | game.min.js:3713
  | (anonymous) | @ | game.min.js:221
  | (anonymous) | @ | game.min.js:232
  | (anonymous) | @ | game.min.js:154
  | a | @ | game.min.js:134
  | t.sendRequest | @ | game.min.js:3705
  | (anonymous) | @ | game.min.js:95336
  | (anonymous) | @ | game.min.js:221
  | (anonymous) | @ | game.min.js:232
  | (anonymous) | @ | game.min.js:154
  | a | @ | game.min.js:134
  | i.listBounties | @ | game.min.js:95330
  | (anonymous) | @ | game.min.js:95272
  | (anonymous) | @ | game.min.js:221
  | (anonymous) | @ | game.min.js:232
  | (anonymous) | @ | game.min.js:154
  | a | @ | game.min.js:134
  | i.getBountyRuns | @ | game.min.js:95267
  | i.loadBounties | @ | game.min.js:132340
  | i.postCreate | @ | game.min.js:132330
  | (anonymous) | @ | game.min.js:5550
  | (anonymous) | @ | game.min.js:221
  | (anonymous) | @ | game.min.js:232
  | (anonymous) | @ | game.min.js:180
  | (anonymous) | @ | game.min.js:232
  | (anonymous) | @ | game.min.js:2610
  | (anonymous) | @ | game.min.js:221
  | (anonymous) | @ | game.min.js:232
  | (anonymous) | @ | game.min.js:154
  | a | @ | game.min.js:134
  | t.completeGeneratorAsync | @ | game.min.js:2605
  | (anonymous) | @ | game.min.js:5280
  | (anonymous) | @ | game.min.js:221
  | (anonymous) | @ | game.min.js:232
  | h | @ | game.min.js:137
  | Promise.then (async) |   |  
  | u | @ | game.min.js:152
  | h | @ | game.min.js:137
  | Promise.then (async) |   |  
  | u | @ | game.min.js:152
  | h | @ | game.min.js:137
  | Promise.then (async) |   |  
  | u | @ | game.min.js:152
  | h | @ | game.min.js:137
  | Promise.then (async) |   |  
  | u | @ | game.min.js:152
  | (anonymous) | @ | game.min.js:154
  | a | @ | game.min.js:134
  | (anonymous) | @ | game.min.js:5260
  | t | @ | game.min.js:2638
  | i.loadFromJSONWithDependencies | @ | game.min.js:5259
  | i.loadWithDependencies | @ | game.min.js:5255
  | i.create | @ | game.min.js:55397
  | i.processConfigObj | @ | game.min.js:8583
  | i.update | @ | game.min.js:8633
  | t.Group.update | @ | phaser-e28c61a564.min.js:1
  | t.Group.update | @ | phaser-e28c61a564.min.js:1
  | t.Stage.update | @ | phaser-e28c61a564.min.js:1
  | updateLogic | @ | phaser-e28c61a564.min.js:1
  | update | @ | phaser-e28c61a564.min.js:1
  | i.update | @ | game.min.js:10604
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1
  | requestAnimationFrame (async) |   |  
  | updateRAF | @ | phaser-e28c61a564.min.js:1
  | window.requestAnimationFrame.forceSetTimeOut._onLoop | @ | phaser-e28c61a564.min.js:1

</span></div></div></div></div></div></div></div><div aria-hidden="true" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 0px; color: transparent;">﻿</div><div class="source-code" id="console-prompt" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; white-space: pre-wrap; font-size: 12px; clear: right; position: relative; margin: 0px 22px 0px 20px; color: rgb(27, 27, 27); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="widget" jslog="TextField; context: console-prompt; track: change, keydown: Enter|ArrowUp|ArrowDown|PageUp" style="box-sizing: border-box; min-width: 0px; min-height: 0px; position: relative; flex: 1 1 auto; contain: style;"><div class="console-prompt-editor-container" style="box-sizing: border-box; min-width: 0px; min-height: 21px;"><devtools-text-editor style="box-sizing: border-box; min-width: 0px; min-height: 0px;"><div class="cm-editor ͼ1 ͼ2 ͼ4 ͼ5" style="box-sizing: border-box; flex-direction: column; position: relative !important; display: flex !important; color: color: var(--sys-color-on-subtle); cursor: auto;"><div class="cm-announced" aria-live="polite" style="position: fixed; top: -10000px;"></div><div tabindex="-1" class="cm-scroller" style="font-family: var(--source-code-font-family); line-height: 1.4em; height: 24.8px; overflow-x: auto; position: relative; z-index: 0; display: flex !important; align-items: flex-start !important; font-size: var(--source-code-font-size);"><div spellcheck="false" autocorrect="off" autocapitalize="off" translate="no" contenteditable="true" class="cm-content cm-lineWrapping" role="textbox" aria-multiline="true" aria-label="Console prompt" data-language="javascript" aria-autocomplete="list" style="margin: 0px; flex-grow: 2; flex-shrink: 1; display: block; white-space: break-spaces; overflow-wrap: anywhere; box-sizing: border-box; min-height: 100%; padding: 4px 0px; outline: none; word-break: break-word; caret-color: transparent !important; line-height: 1.4em; -webkit-user-modify: read-write-plaintext-only; tab-size: 4;"><div class="cm-line" style="display: block; padding: 0px 2px 0px 6px; caret-color: transparent !important;"><br></div></div><div class="cm-layer cm-layer-above cm-cursorLayer" aria-hidden="true" style="position: absolute; left: 0px; top: 0px; contain: size style; pointer-events: none; z-index: 150; animation-duration: 1200ms;"></div><div class="cm-layer cm-selectionLayer" aria-hidden="true" style="position: absolute; left: 0px; top: 0px; contain: size style; z-index: -2;"></div></div></div></devtools-text-editor></div><div class="console-eager-preview" style="box-sizing: border-box; min-width: 0px; min-height: 0px; padding-bottom: 2px; opacity: 0.6; position: relative;"><div class="console-eager-inner-preview" style="box-sizing: border-box; min-width: 0px; min-height: 0px; text-overflow: ellipsis; overflow: hidden; margin-left: 4px; height: 0px; white-space: nowrap; opacity: 0;"></div><devtools-icon role="presentation" name="chevron-left-dot" class="preview-result-icon" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 16px; height: 16px; color: var(--icon-default); vertical-align: sub; position: absolute; box-sizing: border-box; min-width: 0px; min-height: 0px; left: -13px; top: -1px; opacity: 0;"><span style="display: block; width: 16px; height: 16px; background-color: currentcolor; mask: var(--icon-url) center / contain no-repeat; --icon-url: var(--image-file-chevron-left-dot);"></span></devtools-icon></div><devtools-icon role="presentation" name="chevron-right" class="console-prompt-icon" style="flex-grow: 0; flex-shrink: 0; display: inline-block; width: 16px; height: 16px; color: var(--icon-action); vertical-align: sub; position: absolute; box-sizing: border-box; min-width: 0px; min-height: 0px; left: -13px; top: 1.5px; user-select: none;"><span style="display: block; width: 16px; height: 16px; background-color: currentcolor; mask: var(--icon-url) center / contain no-repeat; --icon-url: var(--image-file-chevron-right);"></span></devtools-icon></div></div><div class="console-view-fix-select-all" aria-hidden="true" style="box-sizing: border-box; min-width: 0px; min-height: 0px; height: 0px; overflow: hidden; color: rgb(27, 27, 27); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></div>
</body>
</html>

**Comment by XPMUser** [comment]
I'm forced to click on the back button.

**Comment by Daboss7173** [comment]
There's already an issue that addresses this problem.

https://github.com/Daboss7173/Daboss7173.github.io/issues/156
