### ISSUE TITLE
Frozen in Prodigy Reborn 1.0

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#16]
Why is my character Botanist Gabriel frozen in Prodigy Reborn 1.0?

![Screenshot 2023-04-29 160729](https://user-images.githubusercontent.com/109283781/235322254-e7451ce9-df57-46df-b0a3-ffb31215f183.png)

**Comment by Daboss7173** [comment]
I do not know, I am not the person who created Prodigy Reborn.

**Comment by XPMUser** [comment]
WAIT A MINUTE MAYBE BECAUSE I USED THE CHARACTER IN THE OTHER SITE

**Comment by XPMUser** [comment]
NEVER MIND THIS

**Comment by XPMUser** [comment]
> I do not know, I am not the person who created Prodigy Reborn.

I know the problem, I used Botanist Gabriel in your site/my site/slappygig's site.
