### ISSUE TITLE
2 Pets (1 that evolves from Sweelum and the other one that evolves from the one that's evolved from Sweelum) in your Definitive Edition

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#169]
### What would you like to add?

2 Pets (1 that evolves from Sweelum and the other one that evolves from the one that's evolved from Sweelum)

**Comment by Daboss7173** [comment]
This issue is unecessary as there is already another one that addresses the ice starter pet.
