### ISSUE TITLE
Request (Assets)

### ISSUE THREAD

**Issue by CBKassir** [Daboss7173/Daboss7173.github.io#17]
For modding, how can we access the games' assets? (especially the audio clips of the npcs' voices)
Is it in this link: https://cdn.prodigygame.com/game/assets/ (the link is non-accessible)

**Comment by XPMUser** [comment]
Access Denied

**Comment by CBKassir** [comment]
Yeah, the access is denied

**Comment by Daboss7173** [comment]
> For modding, how can we access the games' assets? (especially the audio clips of the npcs' voices) Is it in this link: https://cdn.prodigygame.com/game/assets/ (the link is non-accessible)

The links are listed in a function called Prodigy.Assets on game.min.js, you can just CTRL+F it, you have to sorta piece the variables together to get your link.
