### ISSUE TITLE
rune run gives this error

### ISSUE THREAD

**Issue by Toonigy** [Daboss7173/Daboss7173.github.io#171]
### What went wrong?

rune run wont work and you know that already

### How can I reproduce this?

I click the blue crystal in harmony island and got a console error.

### What did the console output?

game.min.js:3741 
        
        
        GET https://daboss7173.github.io/game-cortex-server/listBountyRuns?userID=0 404 (Not Found)

**Comment by Daboss7173** [comment]
Thanks for reporting this bug.

However, you've already made two other issues about this situation.
 
https://github.com/Daboss7173/Daboss7173.github.io/issues/156 (open)
https://github.com/Daboss7173/Daboss7173.github.io/issues/161 (closed)

For this reason, I will close and lock this issue so discussion can be continued in the existing thread.

As I've already said in your **second** thread, if you find any new information about something, you should just make a comment on your exising issue, **not** make a new one.

Thank you.
