### ISSUE TITLE
Replace Muffins with Moog for certain versions

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#179]
Muffins was 2014-2015's Shiverchill Mountain's Boss. Moog was supposed to be Dyno Dig Oasis' boss, not Muffins.
![image](https://github.com/user-attachments/assets/906783aa-4665-4da8-ae93-87362a73a3b6)

**Comment by XPMUser** [comment]
If it's already done for all versions, you can close this issue.

**Comment by Daboss7173** [comment]
> Muffins was 2014-2015's Shiverchill Mountain's Boss. Moog was supposed to be Dyno Dig Oasis' boss, not Muffins. ![image](https://private-user-images.githubusercontent.com/109283781/354852354-906783aa-4665-4da8-ae93-87362a73a3b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5ODAwMjgsIm5iZiI6MTcyMjk3OTcyOCwicGF0aCI6Ii8xMDkyODM3ODEvMzU0ODUyMzU0LTkwNjc4M2FhLTQ2NjUtNGRhOC1hZTkzLTg3MzYyYTczYTNiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQyMTI4NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDBkOGQ5ZTg3OTU4NTQ1OGYxNDFmMjlmZDM5NDY2YzBiNGViNDkzZGM3OTZiYzg2Mzk1MjBlNDk3ZmQ5YTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5t0V4UAbs_iFu5D-AXyGd4bX-RRASlXS7-A8yN8IF3A)

Yeah where do I even start here...

This is a problem with your own fork. If this same bug happens on this repository you can make an issue about it. As of now this issue serves practically no purpose as it follows no format and doesn't address anything regarding this repository.
