### ISSUE TITLE
Lights modpack

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#184]
### What would you like to add?

Lights modpack for 1.10.0.

### How would you like this to be implemented? (optional)

Replace Merchants with lights for Firefly Forest, Shiverchill Mountain, Bonfire Spire, Barnacle Cove, and Skywatch.

### Any additional context (optional)

2014-2015's flashing lights

**Comment by Daboss7173** [comment]
OK again I'm just really confused. What do you mean lights... like what?
