### ISSUE TITLE
Trading feature in your Definitive Edition

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#188]
### What would you like to add?

Trading feature in your Definitive Edition

### How would you like this to be implemented? (optional)

Port it and make it work like the Trading system from Roblox.

### Any additional context (optional)

You can trade anything like the Trialmaster's Set with someone using this feature.

**Comment by Daboss7173** [comment]
I'm sorry, but I'm gonna need you to be a bit more specific on this one. How would this even work?
