### ISSUE TITLE
Firefly Forest Nicknamer, Shiverchill Mountain Nicknamer, Skywatch Nicknamer, Bonfire Spire Nicknamer, and Dyno Dig Oasis Nicknamer in your Definitive Edition

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#191]
### What would you like to add?

Firefly Forest Nicknamer, Shiverchill Mountain Nicknamer, Skywatch Nicknamer, Bonfire Spire Nicknamer, and Dyno Dig Oasis Nicknamer in your Definitive Edition

### How would you like this to be implemented? (optional)

Copy and paste the codes from my pde1500 (My Prodigy Definitive Edition in version 1.50.0 mode (open source))'s game.min.js and fix the errors.

### Any additional context (optional)

Add them in case some people don't like any of the nicknames from Clockwork Town and Barnacle Cove, but they really want nicknames.

**Comment by XPMUser** [comment]
More nicknamers have been added to Daboss7173's PDE.

**Comment by Daboss7173** [comment]
Honestly didn't even notice this issue (i know, i'm an idiot) but yeah, sorta just added this on my own time. Took five-ever but it's done :P

Thanks for the issue anyway.
