### ISSUE TITLE
2015-2016's paths & quests about the paths in your Definitive Edition

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#199]
### What would you like to add?

2015-2016's paths & quests about the paths in your Definitive Edition

### Any additional context (optional)

I'm referring to 2015-2016's versions for when you complete all quests for a certain zone & by going to a different zone without having to use the map such as going from Firefly Forest to Shiverchill Mountains & from Shiverchill Mountains back to Firefly Forest.

**Comment by Daboss7173** [comment]
Well I mean it's not like it's an inherently awful idea or anything like that.

The thing is... it's just easier to have all wizards be able to go wherever they want from the beginning. It's a hint of freedom that makes the game feel more open, and I prefer it to the previous map system.

That's just me though.
