### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#2]
If we're modding our own old prodigy game for fun then how do I change the music in mine and etc?

**Comment by Daboss7173** [comment]
You can change music used in a certain zone, by going into game.min.js, importing your music file into the Prodigy.Assets function which stores where each game asset is. Then you can go into the zone you want to change the music in and put: `this.bgm = <your music here>`

**Comment by slappygig** [comment]
and is this going to be a mobile app so we can play on mobile or a offline version?

**Comment by XPMUser** [comment]
I can't find this.bgm = <your music here>

**Comment by XPMUser** [comment]
This attempt muted the battle and the dark tower music for my version 1.11.0 in the mods section.
