### ISSUE TITLE
Mythical Epics in your Definitive Edition

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#204]
### What would you like to add?

Mythical Epics in your Definitive Edition

**Comment by Daboss7173** [comment]
This just straight up wouldn't be feasible to add. Plain and simple.

Besides, the regular epics are **already** in definitive edition, and considering the majority of mythical epics are just reskins of the originals; we get a recipe that wouldn't make for a good addition to the game.
