### ISSUE TITLE
The real version 1.3.1

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#21]
https://www.youtube.com/watch?v=czIA7xIXTwg&ab_channel=JordanHH

**Comment by XPMUser** [comment]
If we could get the knowledge of the real game.min.js for version 1.3.1, we could have brought back this version instead of another copy of 1.16.5.

**Comment by XPMUser** [comment]
Stephanie Animalcatcher and David Wildgirl also played this version before if you time travel.

Larry Heroshirt was in the video.

**Comment by XPMUser** [comment]
JordanHH is Larry Heroshirt

**Comment by Daboss7173** [comment]
Sadly we don't have the main game script for this version, so running isn't gonna be practical in the slightest.
