### ISSUE TITLE
unable to play

### ISSUE THREAD

**Issue by dmessikid** [Daboss7173/Daboss7173.github.io#212]
### What went wrong?

cant get in

### How can I reproduce this?

open the game

### What did the console output?

![image](https://github.com/user-attachments/assets/480c93f8-045e-4fac-b19f-82cf8c7f8a26)

**Comment by dmessikid** [comment]
placeholder image. nothing happened in the console

**Comment by Daboss7173** [comment]
> ### What went wrong?
> cant get in
> 
> ### How can I reproduce this?
> open the game
> 
> ### What did the console output?
> ![image](https://private-user-images.githubusercontent.com/170285224/361272399-480c93f8-045e-4fac-b19f-82cf8c7f8a26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2ODkwOTUsIm5iZiI6MTcyNDY4ODc5NSwicGF0aCI6Ii8xNzAyODUyMjQvMzYxMjcyMzk5LTQ4MGM5M2Y4LTA0NWUtNGZhYy1iMTlmLTgyY2Y4YzdmOGEyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxNjEzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjU2ZGI4YTQ2NTE5Y2MwMzgyNjIyODA4YmFmMDhjZmNmM2ExMTRkMTY2MTMxYzIyOWY0Y2ZkYTZhNGY5NDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jgrbBRaVIRt_Dt3P4X3vTevcvcdxeWW57UFFA94W4Lo)

Huh, never seen that before. Which version is this?

**Comment by Daboss7173** [comment]
> 3.15.3

Do you know which browser you're using? If it's an older one that could be the problem.

**Comment by dmessikid** [comment]
im using chrome and it works for all versions except 3.15.3 btw is harmony island on this version?

**Comment by dmessikid** [comment]
wait i fixed it

**Comment by dmessikid** [comment]
but thanks for your concern

**Comment by Daboss7173** [comment]
> wait i fixed it

Ah ok thanks.
