### ISSUE TITLE
The bug that gliches your game

### ISSUE THREAD

**Issue by 005Konzz** [Daboss7173/Daboss7173.github.io#219]
### What went wrong?

gliched

### Which version?

2.50.0

### How can I reproduce this?

Go to https://xpmuser.github.io/oldprodigy/select/ and select 2.50.0 then click offline mode and then it takes you to a random place and does error 418

### What did the console output?

Logged in as gmail.com

**Comment by XPMUser** [comment]
When I clicked on the offline mode button, I just got the tutorial, also you're reporting a bug from my version instead of Daboss7173's 2.45.0.
