### ISSUE TITLE
Shops and stores

### ISSUE THREAD

**Issue by DinoD6181** [Daboss7173/Daboss7173.github.io#223]
### What went wrong?

The in game shops and stores are not available. They say it's not working

### Which version?

2.50.0

### How can I reproduce this?

By clicking or entering a shop or store

### What did the console output?

nothing, just a ordinary playthrough

**Comment by DinoD6181** [comment]
is there a way to get the right coding for these stores at all.

**Comment by XPMUser** [comment]
> is there a way to get the right coding for these stores at all.



> is there a way to get the right coding for these stores at all.



> is there a way to get the right coding for these stores at all.

Not yet

**Comment by DinoD6181** [comment]
Do you have to code it in or does someone send it to you

**Comment by DinoD6181** [comment]
Do you have to get that from someone.

**Comment by Daboss7173** [comment]
This version isn't even on this site, so I have to close this. Report problems with XPMUser's website on his Discord server, thanks.

**Comment by DinoD6181** [comment]
Yeah there is. i used the link and chose this version. Its there. I dont know what version you're using but for me it's there.

**Comment by Daboss7173** [comment]
> Yeah there is. i used the link and chose this version. Its there. I dont know what version you're using but for me it's there.
https://daboss7173.github.io/oldprodigy/select/

**Comment by Daboss7173** [comment]
I literally own this repository. How I wouldn't know which versions I made on my own site is beyond me.

**Comment by Daboss7173** [comment]
Pretty sure you're talking about XPMUser's website since that does have 2-50-0.

You're supposed to report bugs on XPMUser's site on his Discord server. It's literally right there in his Readme.

https://discord.gg/9HMtcgFQRc
