### ISSUE TITLE
questions about the stores and rune runs

### ISSUE THREAD

**Issue by DinoD6181** [Daboss7173/Daboss7173.github.io#225]
### What would you like to add?

I know that you need a certain Api to work these areas since the prodigy game servers used them, but is it possible to get this Api or will harmony island and the stores always be broken or will you be able to get the Api at some point 

### How would you like this to be implemented? (optional)

I am just wondering if it is entirely possible if you can get the api

### Type of suggestion

Other

### I agree to the following

- [X] By checking this box, I confirm that this issue is NOT about adding a new Prodigy version.
- [X] By checking this box, I confirm that there are no open issues about this suggestion.
- [X] By checking this box, I confirm that this issue template is being used to suggest a feature, not report a bug, and that if I want to make a bug report, I should not be using this issue template.

**Comment by XPMUser** [comment]
Not yet, Render emailed me failed jobs and I don't have a credit card to buy the apis.

**Comment by DinoD6181** [comment]
Oh, so it is possible to get the apis, but they are expensive. Is that why they don't work after a certain version, because of the whole overhaul on stores and rune runs

**Comment by DinoD6181** [comment]
Does that mean in the later future, we can have the stores working again

**Comment by dmessikid** [comment]
yay

**Comment by DinoD6181** [comment]
I do hope in that later on, we can get stores working again. The only good armor you can get without the stores is Mira's robes and scepter

**Comment by DinoD6181** [comment]
I also hope that we can get the dynos since we cant find them outside of the dyno digs oasis store

**Comment by Daboss7173** [comment]
It'll most likely stay like this. Buying APIs isn't even a real problem, the problem lies in the fact that there are no archives of the data used for the stores.

Rune Run is in an even worse state. Literally nobody could even figure out why that didn't work.

-so yeah, it's not something that can be fixed.

**Comment by DinoD6181** [comment]
what about using the APIs from the present stores

**Comment by DinoD6181** [comment]
or using some of the old version store's apis

**Comment by Daboss7173** [comment]
> what about using the APIs from the present stores

The problem there is that they have different items that don't exist in these versions.

> or using some of the old version store's apis

The problem there is that it's formatted differently and is missing items and while shops.

**Comment by XPMUser** [comment]
I can't make game servers due to failed jobs.

**Comment by DinoD6181** [comment]
Is it possible that some of this code could be found or is it gone forever, just completely deleted

**Comment by Daboss7173** [comment]
> Is it possible that some of this code could be found or is it gone forever, just completely deleted

I don't think it can be recovered. Not by me anyway.

**Comment by DinoD6181** [comment]
dang, maybe in the future, someone could find it. Like in the archives of the prodigy code
