### ISSUE TITLE
Water Gargoyle Pets in your Definitive Edition

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#226]
### What would you like to add?

Water Gargoyle Pets in your Definitive Edition

Prodigy Education didn't add Water Gargoyle Pets before the pet art update.

### How would you like this to be implemented? (optional)

Use paint.net to make Water Gargoyle Pets (old style).

### Any additional context (optional)

Once you add them, make them encounterable in Barnacle Cove.

### Type of suggestion

New Prodigy Definitive Edition feature

### I agree to the following

- [X] By checking this box, I confirm that this issue is NOT about adding a new Prodigy version.
- [X] By checking this box, I confirm that there are no open issues about this suggestion.
- [X] By checking this box, I confirm that this issue template is being used to suggest a feature, not report a bug, and that if I want to make a bug report, I should not be using this issue template.

**Comment by DinoD6181** [comment]
Wait, there is a site which allows you to make prodigy pets different styles before and after the major pet design update!?

**Comment by XPMUser** [comment]
> Wait, there is a site which allows you to make prodigy pets different styles before and after the major pet design update!?

Yes https://www.piskelapp.com/ & https://www6.lunapic.com/editor/

**Comment by DinoD6181** [comment]
Dude, thank you. Now all i have to do is figure out how to implement it into the code
