### ISSUE TITLE
Teleporting to a zone with a Google Account gave me an error in the console list.

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#228]
### What went wrong?

Teleporting to a zone with a Google Account gave me an error in the console list.

### Which version?

Your Definitive Edition in 1.50.0 Mode (Version 0.10.6e)

### How can I reproduce this?

Go to any zone with a Google Account.

### What did the console output?

js?l=dataLayer&id=G-7ZTYK6JMPT:152 
        
        
        Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

### I agree to the following

- [X] By checking this box, I confirm that this bug report is being made for a bug that occurred on THIS website (daboss7173.github.io / oldprodigy.onrender.com), and NOT XPMUser's website (xpmuser.github.io)
- [X] By checking this box, I confirm that this issue is being used to report a problem with an existing feature, and not to suggest a new feature.

**Comment by Daboss7173** [comment]
> ### What went wrong?
> Teleporting to a zone with a Google Account gave me an error in the console list.
> 
> ### Which version?
> Your Definitive Edition in 1.50.0 Mode (Version 0.10.6e)
> 
> ### How can I reproduce this?
> Go to any zone with a Google Account.
> 
> ### What did the console output?
> js?l=dataLayer&id=G-7ZTYK6JMPT:152
> 
> ```
>     Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
> ```
> 
> ### I agree to the following
> * [x]  By checking this box, I confirm that this bug report is being made for a bug that occurred on THIS website (daboss7173.github.io / oldprodigy.onrender.com), and NOT XPMUser's website (xpmuser.github.io)
> * [x]  By checking this box, I confirm that this issue is being used to report a problem with an existing feature, and not to suggest a new feature.

That just means you have an adblocker. It's nothing. My site doesn't even show ads (¬_¬ )
