### ISSUE TITLE
The academy is unreachable in prodigy 1.51.0

### ISSUE THREAD

**Issue by Volcannnnnnoon** [Daboss7173/Daboss7173.github.io#230]
### What went wrong?

When I was level 15, the academy was still unreachable. Now I am at level 81 but still the academy is unreachable

### Which version?

1.51.0

### How can I reproduce this?

I have no idea

### What did the console output?

Here you go
![Screenshot 2024-09-26 17 32 09](https://github.com/user-attachments/assets/9d5e57cb-f741-4524-a05f-332117914022)
![Screenshot 2024-09-26 17 32 24](https://github.com/user-attachments/assets/2daf5c5a-db05-4f84-b8e4-a3a2ced5ee3a)

### I agree to the following

- [X] By checking this box, I confirm that this bug report is being made for a bug that occurred on THIS website (daboss7173.github.io / oldprodigy.onrender.com), and NOT XPMUser's website (xpmuser.github.io)
- [X] By checking this box, I confirm that this issue is being used to report a problem with an existing feature, and not to suggest a new feature.

**Comment by Daboss7173** [comment]
Afraid this isn't a bug.

1-51-0 is a version that was made before the Academy was added to the game. If you wanna play a version that has the Academy, I'd suggest 2-20-0 or later.

Thanks.
