### ISSUE TITLE
Wished an ice starter pet was in the old starter pets

### ISSUE THREAD

**Issue by DrawnBeast95422** [Daboss7173/Daboss7173.github.io#233]
### What would you like to add?

There is no ice pet of the 4 old starter pets. I wished an ice pet was also there. I want it to look like Dragic, Dragling and Tarragon whatever name for the ice old starter pets

### Type of suggestion

Other

### I agree to the following

- [X] By checking this box, I confirm that this issue is NOT about adding a new Prodigy version.
- [X] By checking this box, I confirm that there are no open issues about this suggestion.
- [X] By checking this box, I confirm that this issue template is being used to suggest a feature, not report a bug, and that if I want to make a bug report, I should not be using this issue template.

**Comment by XPMUser** [comment]
Sweelum is in Daboss7173's Definitive Edition, you can adopt it during the tutorial or catch it during a battle with it from Shiverchill Mountains.

**Comment by Daboss7173** [comment]
There is an ice starter pet on Definitive Edition, which is sort of a culmination of a bunch of mods I made.

You can try it here:
https://oldprodigy.onrender.com/play

**Comment by DrawnBeast95422** [comment]
Hello this link isn't loading
[image: Screenshot 2024-10-11 12.39.38.png]

**Comment by DrawnBeast95422** [comment]
It is working now

**Comment by DrawnBeast95422** [comment]
Thank you very much for the ice pet it looks like this and it is Sweelum
![Screenshot 2024-10-11 14 48 02](https://github.com/user-attachments/assets/64c92312-f52b-4f5e-9e8f-d5d511e78e3c)
![Screenshot 2024-10-11 14 48 25](https://github.com/user-attachments/assets/3578e078-5bff-424b-a1bf-9226dd74f62b)

**Comment by DrawnBeast95422** [comment]
he looks very much like peeko

**Comment by DrawnBeast95422** [comment]
What are his evolutions?

**Comment by XPMUser** [comment]
> What are his evolutions?

There are no evolutions for Sweelum for now, but they're coming soon.
