### ISSUE TITLE
Buying 10 Milky Way Plushes and 1 Star Jar and then reloading Lamplight Town froze your game.

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#235]
### What went wrong?

Buying 10 Milky Way Plushes and 1 Star Jar and then reloading Lamplight Town froze your game.

### Which version?

Your Definitive Edition in 1.50.0 Mode version 0.11.0

### How can I reproduce this?

Buy 10 Milky Way Plushes and 1 Star Jar and then reload Lamplight Town.

### What did the logs output? (press F12 or CTRL+SHIFT+J to see console logs)

Uncaught Error: set failed: value argument contains NaN in property 'arena.leaders.4G15yz94D9hsF6DPc1W1tcuut4D2.data.starlightFestivalDaily.boughtEventItem'
    at _0x140996 (game.min.js?v=0.11.0:1:799860)
    at game.min.js?v=0.11.0:1:801225
    at _0xd96bc1 (game.min.js?v=0.11.0:1:571199)
    at _0x140996 (game.min.js?v=0.11.0:1:800383)
    at game.min.js?v=0.11.0:1:801225
    at _0xd96bc1 (game.min.js?v=0.11.0:1:571199)
    at _0x140996 (game.min.js?v=0.11.0:1:800383)
    at game.min.js?v=0.11.0:1:801225
    at _0xd96bc1 (game.min.js?v=0.11.0:1:571199)
    at _0x140996 (game.min.js?v=0.11.0:1:800383)

### I agree to the following

- [X] By checking this box, I confirm that this bug report is being made for a bug that occurred on THIS website (daboss7173.github.io / oldprodigy.onrender.com), and NOT XPMUser's website (xpmuser.github.io)
- [X] By checking this box, I confirm that this issue is being used to report a problem with an existing feature, and not to suggest a new feature.

**Comment by Daboss7173** [comment]
Thanks for the report, I'm actively looking into this. Expect it to be fixed soon!
