### ISSUE TITLE
Stuff glitchy

### ISSUE THREAD

**Issue by Old-Prodigy** [Daboss7173/Daboss7173.github.io#238]
### What went wrong?

when battling, your name and health numbers are cracked/broken/hidden

### Which version?

3.15.3

### How can I reproduce this?

battle : 
![image](https://github.com/user-attachments/assets/2cc11a57-e7b6-4435-aeb8-eedb4ce36f17)

### What did the logs output? (press F12 or CTRL+SHIFT+J to see console logs)

![image](https://github.com/user-attachments/assets/02d1bacf-de04-44d7-b4a3-57ece1e05def)

### I agree to the following

- [X] By checking this box, I confirm that this bug report is being made for a bug that occurred on THIS website (daboss7173.github.io / oldprodigy.onrender.com), and NOT XPMUser's website (xpmuser.github.io)
- [X] By checking this box, I confirm that this issue is being used to report a problem with an existing feature, and not to suggest a new feature.

**Comment by Daboss7173** [comment]
Couldn't reproduce this. It's most likely just a visual glitch from an outdated browser. Try updating your browser. (or downloading a newer one that is more up-to-date)

**Comment by Daboss7173** [comment]
![Screenshot_20241126_174544_Chrome](https://github.com/user-attachments/assets/603c1809-bbfa-4db9-8dfc-d6e50d4bba06)
