### ISSUE TITLE
Skywatch Bug in Definitive Edition

### ISSUE THREAD

**Issue by Lunna-Cielo** [Daboss7173/Daboss7173.github.io#241]
### What went wrong?

The second Master Key Piece is nowhere to be found

### Which version?

Definitive Edition

### How can I reproduce this?

![Screenshot 2024-12-15 9 35 51 AM](https://github.com/user-attachments/assets/06fe0847-9695-4d3f-92d4-c75f54012a66)

I don't know if it's a me thing; but it occurred after I picked up the first half of the Master Key

### What did the logs output? (press F12 or CTRL+SHIFT+J to see console logs)

I can't find the log ouput; CTRL+SHIFT+J isn't working

### I agree to the following

- [X] By checking this box, I confirm that this bug report is being made for a bug that occurred on THIS website (daboss7173.github.io / oldprodigy.onrender.com), and NOT XPMUser's website (xpmuser.github.io)
- [X] By checking this box, I confirm that this issue is being used to report a problem with an existing feature, and not to suggest a new feature.

**Comment by Daboss7173** [comment]
> ### What went wrong?
> The second Master Key Piece is nowhere to be found
> 
> ### Which version?
> Definitive Edition
> 
> ### How can I reproduce this?
> ![Screenshot 2024-12-15 9 35 51 AM](https://private-user-images.githubusercontent.com/191789488/395881043-06fe0847-9695-4d3f-92d4-c75f54012a66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MTYxNjMsIm5iZiI6MTczNDYxNTg2MywicGF0aCI6Ii8xOTE3ODk0ODgvMzk1ODgxMDQzLTA2ZmUwODQ3LTk2OTUtNGQzZi05MmQ0LWM3NWY1NDAxMmE2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQxMzQ0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmViOWZkOThhNjM1YWEzYjQ2NmQ4NjE4YTViZjM3M2Q1MjY0NGY0MDhkMjBmOWI2Mjg5NTRkZGMyNTBhMzlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NnZUmUAhQbYfYvdDry9pdSPeRYgAeoDNqwyIxa8SgQk)
> 
> I don't know if it's a me thing; but it occurred after I picked up the first half of the Master Key
> 
> ### What did the logs output? (press F12 or CTRL+SHIFT+J to see console logs)
> I can't find the log ouput; CTRL+SHIFT+J isn't working
> 
> ### I agree to the following
> * [x]  By checking this box, I confirm that this bug report is being made for a bug that occurred on THIS website (daboss7173.github.io / oldprodigy.onrender.com), and NOT XPMUser's website (xpmuser.github.io)
> * [x]  By checking this box, I confirm that this issue is being used to report a problem with an existing feature, and not to suggest a new feature.

It's on the other side of the map. Since it's further away than the other key piece, the hand won't point there at first (which is something that I do need to fix soon) but this has always been a thing in Prodigy.

I'm pretty sure you can just warp to the starting zone and go right and the guide hand should appear again.

**Comment by Lunna-Cielo** [comment]
Yea, I noticed the double hands when I warped to the starting zone again.

I found the other half though; thank you! :D

**Comment by Daboss7173** [comment]
Yeah I got it fixed this morning so now the second hand appears. It just didn't before so I wouldn't blame you XD

Thanks for reporting!
