### ISSUE TITLE
Run the game offline

### ISSUE THREAD

**Issue by marco-the-first** [Daboss7173/Daboss7173.github.io#3]
I'm trying to run the game offline, I fixed all problems with images and files, so all files are loading correctly. but still the game is not running. Is there is any way to fix that?

I guess the problem is because of the websocket, it is getting opened then closed again, that's what I'm getting in console. 

Load GM: ARENA
game.js?v=1a2d722:2972 Load sPN: true
game.js?v=1a2d722:2085 rs
game.js?v=1a2d722:2092 rs:lo
game.js?v=1a2d722:2067 iSI: false
game.js?v=1a2d722:382 start pSC: 3
game.js?v=1a2d722:387 save gm: ARENA
game.js?v=1a2d722:389 save sPN: true
game.js?v=1a2d722:538 Socket opened
game.js?v=1a2d722:540 Socket closed
game.js?v=1a2d722:2528 re
game.js?v=1a2d722:2532 fi_aw
game.js?v=1a2d722:2530 fi_bg

**Comment by slappygig** [comment]
me too i want to run without internet!

**Comment by XPMUser** [comment]
Local intranet/PVZ

**Comment by XPMUser** [comment]
I wish Prodigy was modified by PopCap Games

**Comment by Daboss7173** [comment]
Well it's not gonna work, downloading EVERY file from the Prodigy CDN isn't exactly ideal for this, and that's the only real way to run it offline.
