### ISSUE TITLE
Do you have the following files for version 1.11.0?

### ISSUE THREAD

**Issue by Ao28th28thedev** [Daboss7173/Daboss7173.github.io#36]
1. zone-house.json
2. zone-house.png

**Comment by XPMUser** [comment]
And also the house backgrounds that don't show wizards or the game GUIs on it. zone-house.png?

**Comment by XPMUser** [comment]
game.min.js with the house being like october 28 2014.

**Comment by Daboss7173** [comment]
Nope, I've mentioned this multiple times, I couldn't find those files.
