### ISSUE TITLE
Prodigy Education didn't introduce this zone in 2015 or earlier. (In the tree)

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#40]
How to explore this zone? 
![Screenshot 2023-07-02 130308](https://github.com/Daboss7173/Daboss7173.github.io/assets/109283781/f7bd307e-bb27-4ac4-b744-2d319249be8e)

**Comment by XPMUser** [comment]
This was an unused zone.

**Comment by Daboss7173** [comment]
That's the fun part, you don't.
