### ISSUE TITLE
How to get a 2015 version of a math problem?

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#41]
![Screenshot 2023-07-02 163911](https://github.com/Daboss7173/Daboss7173.github.io/assets/109283781/305385be-a737-4bbf-b8f2-f64bf46adf91)

**Comment by XPMUser** [comment]
I miss the close button at the bottom.

**Comment by Daboss7173** [comment]
You can't, it just doesn't work.
