### ISSUE TITLE
The state choosing area can't be passed or skipped through even when the country/city/state is selected.

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#43]
'Where do you live?' can still be passed through in prodigygame.com.
![Screenshot 2023-08-05 092011](https://github.com/Daboss7173/Daboss7173.github.io/assets/109283781/7c984174-5d8e-4299-91fa-6a772d668dba)

I told a few people who have this problem to click on the offline mode button instead of the new student button.

**Comment by XPMUser** [comment]
At least North Korea isn't on the list due to ban on Prodigy in North Korea.

**Comment by Daboss7173** [comment]
I already finished the new character system. I just had to upload it.
