### ISSUE TITLE
Pippet during battle time

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#45]
He's invisible during battle time and he makes the game freeze by attempting to cast a spell.

Shadow Shock Vs. The Game Freezer

**Comment by XPMUser** [comment]
Version 1.60.0

**Comment by Daboss7173** [comment]
I got the spine plugin working, if it still doesn't work you can let me know.

**Comment by Daboss7173** [comment]
Ok yeah I just tested it works flawlessly now.
