### ISSUE TITLE
Chef's Attire

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#51]
![Screenshot 2023-08-10 120730](https://github.com/Daboss7173/Daboss7173.github.io/assets/109283781/eb7ad566-87c4-41e2-b035-d78ca23ae702)

**Comment by XPMUser** [comment]
4 Black and green squares

**Comment by Daboss7173** [comment]
This isn't a bug, this item just didn't exist in this version.
