### ISSUE TITLE
I can't do the following unless you connect Daboss7173.github.io to Prodigy Education's servers:

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#54]
1. PVP
2. Make friends in the game
3. Take part in the arena
4. Play on a world to see other wizards being actual players.

**Comment by XPMUser** [comment]
3 things are still possible in new Prodigy (prodigygame.com).

**Comment by Daboss7173** [comment]
This isn't really a bug, these are just side effects of playing in offline mode.
