### ISSUE TITLE
The Titan Grounds Zone reminds me of the In the Tree zone.

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#55]
![Screenshot 2023-08-17 160936](https://github.com/Daboss7173/Daboss7173.github.io/assets/109283781/d352169a-67de-44de-a8cd-f872a1f2d1f2)
![Screenshot 2023-08-17 160947](https://github.com/Daboss7173/Daboss7173.github.io/assets/109283781/c49245fb-8c40-441e-bf7f-17ee1ee6725c)

**Comment by Daboss7173** [comment]
Not an issue, it just crashes the game on load because it requires prodigy's multiplayer api and titan api, which isn't something that can be directly accessed like that.
