### ISSUE TITLE
Request for all versions?: change walk speed like reborn 

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#57]
Reborn has fast walk speed so j would like to see that in prodigy classic too

**Comment by XPMUser** [comment]
I can do that for Cookie

**Comment by XPMUser** [comment]
Vanilla versions of Prodigy wouldn't have higher walk speed for the wizards.

**Comment by Daboss7173** [comment]
I'm working on an advanced modpack system already. I think this is a good first mod to feature.

**Comment by Daboss7173** [comment]
Woops! Didn't mean to close. My bad.

**Comment by XPMUser** [comment]
Is this a bug?

> Woops! Didn't mean to close. My bad.

**Comment by slappygig** [comment]
What's the Modpack system and what does it do?

**Comment by Daboss7173** [comment]
That's for me to know, and for you to find out.

**Comment by Daboss7173** [comment]
The mod-pack system is finished, and the walkspeed mod (with a slider rather than 2 buttons) is out too.
Ima close this

**Comment by XPMUser** [comment]
I hope slappygig fixes 1-7-0 soon.

**Comment by XPMUser** [comment]
I can't get it to work in xpmuser.github.io.
