### ISSUE TITLE
Arena multiplayer account mod

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#58]
What would you like to add: 
Arena, multiplayer and accounts.

How would you want it to be implemented:
Arena so we can get like draconyx gear, multiplayer for Arena to work and accounts so we don't have to go to options and press save.
Any additional context:
People with poor internet playing 1.51 and newer wouldn't  have to worry about their progress not starting where they are before if this mod is real.

**Comment by XPMUser** [comment]
Multiplayer uses the API.

**Comment by XPMUser** [comment]
You can get Draconyx stuff by editing your character file.

**Comment by Daboss7173** [comment]
> Arena Battles and Multiplayer Mode use the API and also, you're supposed to use a character file, not an account on Old Prodigy.

He means modifying it so that multiplayer and accounts are added in (with a custom-made api)

**Comment by Daboss7173** [comment]
I'm not so sure about the multiplayer, I think the official game should be the home of that, I'm not trying to replace the official game with the old version.

However accounts are actually a really good idea, and if I could rewrite the entire API and math system by myself (which I can't) I would totally consider it.
