### ISSUE TITLE
New fast stuff for 1.30

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#59]
What would you like to add: 
Make the "battle!" text and stuff faster
How would you want it to be implemented:
Make the text in battle fast including animations in battle.
Any additional context:

**Comment by XPMUser** [comment]
Change the speed from game.min.js.

**Comment by Daboss7173** [comment]
So basically just faster game speed. easy.

**Comment by Daboss7173** [comment]
Yeah this is done so ima close
