### ISSUE TITLE
Android app?

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#60]
What would you like to add: 
An old prodigy mobile app
How would you want it to be implemented:
An android app of old prodigy so we can't accidentally like for example tap the refresh button on the browser we are using and also fullscreen so it will be nice

Any additional context:
I think I highly recommend you don't put it on appstore due to copyright dmca stuff, I made a app for 1.51 but didn't work well so if I'll try again but for 2.6.0 and a better app maker site, if you don't make the apk then that's fine.

**Comment by XPMUser** [comment]
I tried Old Prodigy on a mobile device with a browser.

**Comment by Daboss7173** [comment]
It's a really good idea, but I just don't know how to do it, in fact, I don't really know how Android apps work AT ALL. Plus, maintaining a browser version AND a mobile version all on my own would be a pain. Just trying to maintain 15+ versions of Prodigy and keep enhancements made on certain versions made available to other versions as quickly as possible is challenging enough, and could easily keep me busy for months.

Essentially, I just don't have the time on my hands to be able to do so. It may not be the ideal way to play, but it is definitely still playable on a mobile browser.
