### ISSUE TITLE
Prodigy Version 1-12-2

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#62]
What would you like to add: 
1-12-2
How would you want it to be implemented:
Just like May 2015's Prodigy, but with 1-16-5's leaderboards style, not with the unused leaderboards design.
Any additional context:
You can download 1-12-2's files and folders from xpmuser.github.io.

**Comment by XPMUser** [comment]
1-12-2 doesn't have a problem with all the zones except for the house.

**Comment by Daboss7173** [comment]
I'm only hosting actual Prodigy versions, that are actually somewhat playable. This is just a theoretical recreation based on 1-11-0, which isn't what I'm trying to do.

**Comment by XPMUser** [comment]
I'm the only one who has 1.12.2

**Comment by XPMUser** [comment]
https://www.youtube.com/watch?v=sbFnEd2HrH0 This video has 1-12-2
