### ISSUE TITLE
Game freezes after getting all factory parts in skywatch

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#63]
What went wrong:
1.30 has this bug where if you get the 5th factory part, it freezes after battle.
How can I replicate this:
I got the last factory part benni told me to get, and after a battle getting the 5th part it freezes my game.
Console log output (optional):

**Comment by XPMUser** [comment]
I had the same problem too.

**Comment by Daboss7173** [comment]
I have no idea what I'm looking for, a console log output would be great here.

**Comment by XPMUser** [comment]
Even I can't fix this bug.

**Comment by Daboss7173** [comment]
Well there's no logs and I can't really reproduce this natively. I'm just gonna close this.
