### ISSUE TITLE
Found version 3.0.0

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#64]
What would you like to add: 
3-0-0 version

How would you want it to be implemented:
I found 3.0.0

Any additional context:
Game.min.js is http://cdn.prodigygame.com/game/play/production/3-0-0/game.min.js

**Comment by XPMUser** [comment]
I've used this version on the real Prodigy site before.

**Comment by XPMUser** [comment]
I feel bad for P4NDAGIRL Z

**Comment by Daboss7173** [comment]
There are a lot of versions between 2-6-0 and this version. I wanna cover those before this version so it's not too stark of a transition. I have plans right now to cover more earlier versions, although I will cover 3-0-0 at some point, it's definitely not priority number 1.
