### ISSUE TITLE
1-99-0

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#65]
What would you like to add: 
Prodigy version 1-99-0
How would you want it to be implemented:
Here is its game.min.js: http://cdn.prodigygame.com/game/play/production/1-99-0/game.min.js
Any additional context:

**Comment by XPMUser** [comment]
I remember this version.

**Comment by XPMUser** [comment]
This is beta testing

> What would you like to add: Prodigy version 1-99-0 How would you want it to be implemented: Here is its game.min.js: http://cdn.prodigygame.com/game/play/production/1-99-0/game.min.js Any additional context:

**Comment by Daboss7173** [comment]
I don't think I'm gonna do this version. There aren't really any significant changes in it, and if there aren't significant changes then it's not a version worth doing.
