### ISSUE TITLE
Cannot move on Prodigy 1.24.0

### ISSUE THREAD

**Issue by upixo-host** [Daboss7173/Daboss7173.github.io#69]
What went wrong:
I can't move the character (ignore the character's name)

https://github.com/Daboss7173/Daboss7173.github.io/assets/144474999/2a8c9ab3-6149-48fc-9065-b36f4292e680

How can I replicate this:
Just try to move the character (maybe it's glitching because i'm on firefox)

Console log output:

Experiment next-generation-accessibility-engine-powering-screen-readers has unknown featureId: accessibilityCache [RemoteSettingsExperimentLoader.sys.mjs:596:21](resource://nimbus/lib/RemoteSettingsExperimentLoader.sys.mjs)
Experiment next-generation-accessibility-engine-powering-screen-readers-and-other-ats-copy has unknown featureId: accessibilityCache 2 [RemoteSettingsExperimentLoader.sys.mjs:596:21](resource://nimbus/lib/RemoteSettingsExperimentLoader.sys.mjs)
BackgroundUpdate: maybeScheduleBackgroundUpdateTask: Error removing old task: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWinTaskSchedulerService.deleteTask]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/TaskSchedulerWinImpl.sys.mjs :: deleteTask :: line 50"  data: no] [BackgroundUpdate.sys.mjs:589](resource://gre/modules/BackgroundUpdate.sys.mjs)
BackgroundUpdate: maybeScheduleBackgroundUpdateTask: exiting after uncaught exception in maybeScheduleBackgroundUpdateTask! NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWinTaskSchedulerService.registerTask]
    registerTask resource://gre/modules/TaskSchedulerWinImpl.sys.mjs:41
    registerTask resource://gre/modules/TaskScheduler.sys.mjs:119
    _registerBackgroundUpdateTask resource://gre/modules/BackgroundUpdate.sys.mjs:351
[BackgroundUpdate.sys.mjs:655](resource://gre/modules/BackgroundUpdate.sys.mjs)
SearchSuggestionController found an unexpected string value: HTTP request timeout [SearchSuggestionController.sys.mjs:646:17](resource://gre/modules/SearchSuggestionController.sys.mjs)
this.window.gBrowserInit is undefined [ext-browser.js:1134](chrome://browser/content/parent/ext-browser.js)

**Comment by Daboss7173** [comment]
AH this is a problem with your version, you didn't upload a necessary lib, easystar.

https://187.neocities.org/prodigy/1-24-0/js/easystar-0.4.4.min.js

You should upload easystar from this github to your neocities site, it should work then.

**Comment by azf3** [comment]
Thanks!

**Comment by azf3** [comment]
Yes i have two accounts
