### ISSUE TITLE
Older versions won't accept future things.

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#7]
For example: Black Fang Gear in version 1.11.0 attempt

**Comment by Daboss7173** [comment]
Yeah that doesn't exist in those versions for obvious reasons.

**Comment by XPMUser** [comment]
> Yeah that doesn't exist in those versions for obvious reasons.

Imagine seeing Big Hex in Lamplight Academy.

**Comment by XPMUser** [comment]
I practiced Jainism
