### ISSUE TITLE
The saves from earlier than 2-6-0 don't even work in 2-20-0.

### ISSUE THREAD

**Issue by Ao28th28** [Daboss7173/Daboss7173.github.io#70]
What went wrong:
Error using the 2015-2018 saves except for the ones from 2-6-0.
How can I replicate this:
Unknown
Console log output:
2015-2018 except for 2-6-0 saves error

**Comment by Daboss7173** [comment]
Yeah, that's because I've only added 2-6-0 so far. Not a bug.
I'm adding other version later on down the line, but I've gotta convert other versions to the new system.
