### ISSUE TITLE
Sir Vey's question in 2-30-0

### ISSUE THREAD

**Issue by Ao28th28** [Daboss7173/Daboss7173.github.io#71]
What went wrong:
Only the done button is displaying on the menu panel.
How can I replicate this:
Fix the survey thing
Console log output:
I can't find anything about this problem in Developer Tools.

![Screenshot 2023-09-19 204323](https://github.com/Daboss7173/Daboss7173.github.io/assets/122099346/18a3f8e3-c5b7-4d1b-9ad0-d303e4464099)

**Comment by Daboss7173** [comment]
It's a bug due to non-existent survey data trying to be loaded.

The functionality is removed now, so there's at least no softlock.

**Comment by Ao28th28** [comment]
I remember the non-existent survey data back in late 2018/early 2019.
