### ISSUE TITLE
1-50-0 xp bar animation isnt fast

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#72]
What would you like to add: 
Make the xp bar fill animation fast

How would you want it to be implemented:
1-50-0 gives stars after attacking your opponent, I want the exp bar animation fast too

Any additional context:

**Comment by Ao28th28** [comment]
Try changing the numbers of the speed on any js.

**Comment by Daboss7173** [comment]
> Try changing the numbers of the speeds on any js files.

That's not how this works, but ok.

**Comment by Daboss7173** [comment]
> What would you like to add: Make the xp bar fill animation fast
> 
> How would you want it to be implemented: 1-50-0 gives stars after attacking your opponent, I want the exp bar animation fast too
> 
> Any additional context:

Yeah overall really good idea, should be able to speed that up once I'm home tomorrow.

**Comment by Daboss7173** [comment]
Yeah this is done so ima close.
