### ISSUE TITLE
Fireflies, frozen something and bounties all day

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#73]
What would you like to add: 
In 1.50.0, I want to do bounties, get fireflies and frozen somethings without waiting a day

How would you want it to be implemented:
Make it so you don't have to wait until tomorrow to get more fireflies, frozen somethings and do more bounties.
Any additional context:

**Comment by Ao28th28** [comment]
@slappygig Can you put 1-10-0 on your site?

**Comment by Daboss7173** [comment]
I don't think this is something I wanna add because the whole being daily thing is part of the gimmick.
