### ISSUE TITLE
2.45.0 spell delay

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#77]
What went  wrong:
Instead of casting spell Immediately it delays for a few secs.

How can I replicate this:
Pressed the spell button but I have to wait a few secs to cast my spell.

Console log output:

**Comment by Ao28th28** [comment]
I'm experiencing this too

**Comment by Ao28th28** [comment]
No wonder the game froze on my client side.

**Comment by Daboss7173** [comment]
That's not a bug, there are All Out Attacks in this version. All that is, is waiting for the energy meter animation to finish.
If you wait a couple seconds before casting your spell, you'll see there's no delay.
