### ISSUE TITLE
2.45.0 speed mod

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#78]
What would you like to add: 
Speed mod for 2.45.0

How would you want it to be implemented:
1.50 and 1.30 has speed mods so why not for 2.45 too?

Any additional context:

**Comment by Ao28th28** [comment]
I don't know how to apply speed mods for the other versions.

**Comment by Daboss7173** [comment]
I'll see what I can do when I get home, although I'm not sure if the Spine animations will be able to be sped up yet.

**Comment by Daboss7173** [comment]
Alright this is done ima close.
