### ISSUE TITLE
Add an in-game hack menu

### ISSUE THREAD

**Issue by Nigeel** [Daboss7173/Daboss7173.github.io#79]
Since old prodigy versions don't tie with the modern one, I believe it is safe to add an in game hack menu so players don't have to look for hacks that work on the github and so that it is a lot easier to just test stuff out in the old version

My biggest hope if it does get added is that no items are missed from any of the versions so we don't have to do any extra stuff to add them(example: Manually editing files of wizards just to add items). Another thing I hope for is that you can get every pet, every item, every piece of furniture, tower town piece, relic, key item, morph marble, etc.

I also would like if the "what does your wizard look like" screen had everything face cosmetic in it so we don't have to wait for another problem that exists in the modern versions to be patched.

I also would really like if you patched the whole issue where you can't open the shops in the newer versions of prodigy. Although I like the OG versions my favorite one was just before they ever decided to change the design of prodigy.

Although some of these might not make it into the repository I hope this will at least get looked into by somebody in the community(Or maybe even an outsider will hear my beckoning call)

Thanks!
‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ Nigeel

**Comment by Daboss7173** [comment]
Not a bad idea. Since old prodigy is FAR more insecure then modern prodigy it would be relatively simple to add cheats as an optional mod. It would also mean that people wanting to cheat by editing their save (of which there is a lot of) wouldn't have to deal with the game not cooperating with the save editing. It would be safer.

**Comment by Daboss7173** [comment]
The shops not opening in the later versions isn't something I can fix, it involves Prodigy's API's which isn't something any ol' website can access.

**Comment by Daboss7173** [comment]
Alright well I'm putting this on the backburner for now. It's a pretty good idea but for now I don't feel like developing cheats for my own game.

I'll close this for now, but I will still work on it on my own time and once it's finished, it'll be released.
