### ISSUE TITLE
Can you bring back more old versions?

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#8]
Like version 1.10.0 and earlier?

**Comment by XPMUser** [comment]
I remember when clockwork town didn't exist but no way to face the stage game.

**Comment by XPMUser** [comment]
I miss team setting first instead of just battle first.

**Comment by XPMUser** [comment]
Plz don't remove any version

**Comment by XPMUser** [comment]
I miss gaining 5000 gold just for starting as a new student.

**Comment by Daboss7173** [comment]
1.11.0 was the earliest version I could get to work because most assets I just couldn't find on the internet anymore unfortunately.

**Comment by XPMUser** [comment]
Ask Rohan Mahimker or Alexander Peters for the actual game.min.js for earlier versions than 1.11.0 then

**Comment by XPMUser** [comment]
5000 gold was my pastime

**Comment by XPMUser** [comment]
Conner Monstertamer moment

**Comment by XPMUser** [comment]
Stephanie Animalcatcher/Botanist Gabriel/Gabriel the W12-4RD moment

**Comment by XPMUser** [comment]
I got version 1.10.0 and 1.9.0 to work.

**Comment by XPMUser** [comment]
Even 1-8-9
