### ISSUE TITLE
Add a wizard gacha life 2 mod in 1.10.0?

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#81]
What would you like to add: 
A 1.10.0 gacha life 2 art style mod.

How would you want it to be implemented:
Maybe the wizard can be gachalife 2 style. I chose 1.10.0 because there's less outfits so I dont waste time.
Addtional context:
You don't have to make the assets, I will. For now I will post a image of a white blank avatar in a outfit, for skins I will make them with white clothes, white clothes so no nude ness lol. The concepts will have the gacha life 2 avatars in a stand pose. Any outfits not made yet will be white clothes until that outfit is made.

**Comment by Daboss7173** [comment]
Alright yeah I can do the coding stuff. Why not?

Seems like it could be fun. Also yeah. No nude stuff. This is a kids game lmao

**Comment by Daboss7173** [comment]
And besides I've spent so much time modding old versions of prodigy that I know the ins and outs pretty dang well anyway. Should be pretty trivial.

**Comment by Ao28th28** [comment]
Thunderstorm to snowy stuff

**Comment by slappygig** [comment]
![Screenshot_2023-10-16_160207](https://github.com/Daboss7173/Daboss7173.github.io/assets/96138262/615e1a1f-44ef-4a13-b723-e5fdef812d1b)
![Screenshot_2023-10-16_160317](https://github.com/Daboss7173/Daboss7173.github.io/assets/96138262/d4757dd2-ae64-4789-b49a-240913934631)
![Screenshot_2023-10-16_160222](https://github.com/Daboss7173/Daboss7173.github.io/assets/96138262/0508cf5e-badb-451a-bae4-22f14199ba27)
Here is a pink eye face for girls, and the fire robe for both boy and girl

**Comment by slappygig** [comment]
![Screenshot_2023-10-16_160618](https://github.com/Daboss7173/Daboss7173.github.io/assets/96138262/933e6f0a-3bf9-43d2-8c0b-fb55b878bde0)
Yellow hair for boy avatars

**Comment by Daboss7173** [comment]
Ok here's a little bit of needed specificity. There's gonna need to be 16 frames of animation for the outfits, and 4 frames of animation for the hair.

The 4 frames for the hair will be played when they walk.
Same goes for hats.

8 of the outfit frames are gonna be for the idle pose. The other 8 are played when they walk.

It's just a regular transparent spritesheet for all of em.

The wands are just a single image.

Also, each item has an icon and those will most-likely need to be re-done as well.

**Comment by Daboss7173** [comment]
Also u can just send it on Discord, don't wanna crowd up the issue lol

**Comment by Daboss7173** [comment]
Well this is inactive and I'm not getting sent the assets so ima just close this.
