### ISSUE TITLE
Prodigy definitive edition needs info

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#83]
I heard somebody saying definitive edition is 1.50.0, can info about definitive version be added to avoid confusion and also where to check for updates?

**Comment by Daboss7173** [comment]
It's a modded version of 1-50-0 with a buncha enhancements added on top of it.

I'll add more info to the readme pretty soon, it's gonna stay closed-source though.

**Comment by Ao28th28** [comment]
![Screenshot 2023-10-23 210424](https://github.com/Daboss7173/Daboss7173.github.io/assets/122099346/ac30c742-480e-4622-a893-a9fcde55d46b)
