### ISSUE TITLE
Page to see upcoming updates and versions?

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#84]
What would you like to add: 
A page like a news page so we can see upcoming versions, updates and etc

How would you want it to be implemented:
A page with upcoming updates info
Any additional context:
I would like a version with the new arena with runes in it.

**Comment by Daboss7173** [comment]
I think the update page is a good idea, already in the works. There will only be one Definitive Edition though. It'll be much easier to sustain that way.

**Comment by Daboss7173** [comment]
Since the mail has been added back now, and that essentially serves as an update page im gonna close this.
