### ISSUE TITLE
Definitive edition problem

### ISSUE THREAD

**Issue by slappygig** [Daboss7173/Daboss7173.github.io#86]
What went wrong:
When noot says "hey listen" I can't click next

How can I replicate this:
Clicking next when noot says "hey listen" to me after he came in my house doesn't work

Console log output:

**Comment by Daboss7173** [comment]
Yeah I'm already aware of this. It only happens on mobile for some reason. It's pretty strange. For now just play on a computer, since it IS meant to be played that way anyway.

I am looking into this though. I'll close when it's fixed.

**Comment by slappygig** [comment]
I cant be on pc most of time

**Comment by wind40** [comment]
This is the only way I could contact you, I have a few questions (and yes, this IS really the only way.)
1. Is there multiplayer? (_Are the players there real?_)
2. Is there a way to create an account whether it be through the Wayback Machine, hacking, etc?
3. I play 1.5.0, is there a certain version where players (_see question 1_) are more active?
4. How do I get clothes, not from certain places but in Lamplight Town?
5. What are your opinions on the new art style?

**Comment by Daboss7173** [comment]
> This is the only way I could contact you, I have a few questions (and yes, this IS really the only way.)
> 
> 1. Is there multiplayer? (_Are the players there real?_)
> 2. Is there a way to create an account whether it be through the Wayback Machine, hacking, etc?
> 3. I play 1.5.0, is there a certain version where players (_see question 1_) are more active?
> 4. How do I get clothes, not from certain places but in Lamplight Town?
> 5. What are your opinions on the new art style?

Ah, if you're talking abt XPMUser's site, all versions 1.10.0 and below are actually just 1.10.0

Anyway there's no multiplayer, the wizards are bots.

Actual online accounts, whether it be authenticated with google or any other way isn't possible, although you can create wizards, they are locally saved on your computer.

Nah, being that there is no actual players, there ARE no actual players. It's all offline mode. 1.11.0 and 1.10.0 and the fake versions are the only ones with the bots though.

Xpmuser removed the store from versions before 1.10.0 for some reason, so that's a no.

I honestly really like it, right now it's still a bit uncanny because it's still mixed in with a buncha older stuff, but overall I think it's real cool. It doesn't have the crazy detail and shading from the older versions, but it's easier especially for younger kids to grasp, so I can see why they switched to a more simple style later on down the line.

**Comment by fortyuth** [comment]
> Anyway there's no multiplayer, the wizards are bots.

Actual online accounts, whether it be authenticated with google or any other way isn't possible, although you can create wizards, they are locally saved on your computer.

Nah, being that there is no actual players, there ARE no actual players. It's all offline mode. 1.11.0 and 1.10.0 and the fake versions are the only ones with the bots though.

Are you guys working on servers? That would be awesome, though I imagine it would be tough... is this project supposed to be similar to Prodigy Reborn? (RIP)

**Comment by Daboss7173** [comment]
> > Anyway there's no multiplayer, the wizards are bots. Actual online accounts, whether it be authenticated with google or any other way isn't possible, although you can create wizards, they are locally saved on your computer. Nah, being that there is no actual players, there ARE no actual players. It's all offline mode. 1.11.0 and 1.10.0 and the fake versions are the only ones with the bots though.
> 
> Are you guys working on servers? That would be awesome, though I imagine it would be tough... is this project supposed to be similar to Prodigy Reborn? (RIP)

Yeah definitive edition is my own little project meant to be kinda like a Prodigy Reborn, but a whole lot beefier.

I have plans to make an authentication and even a multiplayer system at some point.

Put simply, I got some big plans for Prodigy Definitive Edition.

**Comment by fortyuth** [comment]
> I have plans to make an authentication and even a multiplayer system at some point.

Are you already/soon going to work on it? What are the problems (otherwise the obvious cost of servers?)
How long do you think the overall multiplayer will work (even without the authentication, maybe in a beta?)

**Comment by fortyuth** [comment]
Oh, also if I'm using this account it means I'm at school.

**Comment by Daboss7173** [comment]
Oh cool.

Yeah I have plans to work on it this weekend. I still got a lot of stuff to do though, it's in wayy early stages.

Also yeah, it will probably work before I do accounts, although I think I'm gonna make a proper account system first, mainly because I still got a lot to learn about backend development. I don't really have a release date in mind, I would prefer it to be done sometime before 2024, it could be longer though.

**Comment by fortyuth** [comment]
Are you only working with a few people/solo? What's the past/current/forward roadmap (even though it's in early stages?)

**Comment by Daboss7173** [comment]
> Are you only working with a few people/solo? What's the past/current/forward roadmap (even though it's in early stages?)

It's just me. No roadmap as of yet, just got a rough idea in my head. Still need to get that worked out.

**Comment by fortyuth** [comment]
**I have one big question and some small questions. Are you going to be able to pay for this?**
Why don't you get the system from Prodigy Reborn?
I have a feeling that would work well. Also... what about servers?
Are there different worlds, or will there only be a few so it costs less?
Do you think we could get people to code the multiplayer and implement authentication?

**Comment by Daboss7173** [comment]
> **I have one big question and some small questions. Are you going to be able to pay for this?** Why don't you get the system from Prodigy Reborn? I have a feeling that would work well. Also... what about servers? Are there different worlds, or will there only be a few so it costs less? Do you think we could get people to code the multiplayer and implement authentication?

I think it's a bit too early to be able to answer any of those questions yet, I'm gonna be doing pretty much everything by myself.

I don't really know what you mean by that second question though. Prodigy Reborn doesn't have any more multiplayer functionality than Definitive Edition.

**Comment by fortyuth** [comment]
Huh. Well, I hope you can get enough work and sleep in this weekend for it or something

**Comment by fortyuth** [comment]
How much do you think you could get down over the weekend?

**Comment by slappygig** [comment]
I still can't click the next button

**Comment by Daboss7173** [comment]
> I still can't click the next button

It seems to be a problem with Phaser, not with Prodigy, so not something I can fix.

**Comment by fortyuth** [comment]
I have one more question... How much did you get in over this weekend? (sleep and multiplayer coding)
