### ISSUE TITLE
I got teleported to the login/boot zone instead of doing the 2nd round at the epics subspace in 2-45-0.

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#89]
What went wrong:
Instead of the 2nd round, the game teleports me to the boot/login zone.
How can I replicate this:
Unknown
Console log output:
Unknown

https://github.com/Daboss7173/Daboss7173.github.io/assets/109283781/290369d5-2b22-4640-bd1d-baac164859fe

**Comment by Daboss7173** [comment]
Thank you. I managed to replicate this and know how to fix it now. It reloads the page once the slot machine is unloaded.

I'll fix this once I'm back from school

**Comment by Daboss7173** [comment]
It's fixed now
