### ISSUE TITLE
There is no sir vey

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#9]
Sir Vey can only be found in real Prodigy.

**Comment by XPMUser** [comment]
Sir Vey only appears in the real prodigy site

**Comment by Daboss7173** [comment]
Yeah I removed it because it caused multiple crashes

**Comment by XPMUser** [comment]
How does botanist Gabriel get pizza?

**Comment by XPMUser** [comment]
> Yeah I removed it because it caused multiple crashes

Looks like the only way to get pizza is to edit the txt and play a version that accepts modified txts.

**Comment by XPMUser** [comment]
Can you delete this issue?
