### ISSUE TITLE
The music doesn't loop after exiting out of the stage or dig site.

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#91]
What went wrong:
The music doesn't loop after exiting out of the stage or dig site in earlier than 1.23.7.
How can I replicate this:
Unknown
Console log output:
Unknown

**Comment by XPMUser** [comment]
The music was still looping back in 2015 on the original Prodigy site even after exiting out of a minigame.

**Comment by Daboss7173** [comment]
It's been fixed.
