### ISSUE TITLE
The twilight wheel has been replaced with the bounty board item.

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#92]
What went wrong:
The twilight wheel has been replaced with the bounty board item in your Definitive Edition.
How can I replicate this:
Replace the bounty board item back with the twilight wheel and put the bounty board item back where it was in 2017.
Console log output:
Unknown

**Comment by XPMUser** [comment]
I removed the bounty board item for pde2019 due to the store using the api and it's pointless.

**Comment by slappygig** [comment]
Overhaul? So thats why it's 3.4 still? 
Will the overhauled version have new features or multiplayer?

**Comment by XPMUser** [comment]
> Overhaul

Yes

**Comment by XPMUser** [comment]
> Overhaul? So thats why it's 3.4 still? Will the overhauled version have new features or multiplayer?

Yes

**Comment by XPMUser** [comment]
> So when will overhaul be released?

I dunno

**Comment by slappygig** [comment]
What will definitive edition have

**Comment by Daboss7173** [comment]
> Overhaul? So thats why it's 3.4 still? Will the overhauled version have new features or multiplayer?

Yeah it's 0.3.4 because I'm basically building a whole new code base right now for Definitive Edition. It means I'll actually be able to use build tools which'll be a big plus which'll make it easier to make larger changes more quickly. The overhaul is more internal then external though, so major features like google auth and stuff won't be out yet, it'll be in the works though.

I honestly don't know when I'll be done with it, transitioning to a completely different code base takes some work. Should be by the end of the year though.

**Comment by XPMUser** [comment]
> Well since I'm working on a complete overhaul of Definitive Edition right now, this (and the other issues) will be a while before they are fixed.

I read this one

**Comment by XPMUser** [comment]
> > Overhaul? So thats why it's 3.4 still? Will the overhauled version have new features or multiplayer?
> 
> Yeah it's 0.3.4 because I'm basically building a whole new code base right now for Definitive Edition. It means I'll actually be able to use build tools which'll be a big plus which'll make it easier to make larger changes more quickly. The overhaul is more internal then external though, so major features like google auth and stuff won't be out yet, it'll be in the works though.
> 
> I honestly don't know when I'll be done with it, transitioning to a completely different code base takes some work. Should be by the end of the year though.

Okay

**Comment by Daboss7173** [comment]
0.4.0b is finally out and this is fixed now
