### ISSUE TITLE
The prodigy save converter feature that can automatically convert any save to a save for another version without any errors.

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#94]
What would you like to add: 
The prodigy save converter feature.
How would you want it to be implemented:
Have it convert any save to a save for another version for example: 2-45-0 to earlier than 2-20-0.
Any additional context:
Unknown

**Comment by Daboss7173** [comment]
> What would you like to add: The prodigy save converter feature. How would you want it to be implemented: Have it convert any save to a save for another version for example: 2-45-0 to earlier than 2-20-0. Any additional context: Unknown

That's not gonna work because it'll lead to data loss
