### ISSUE TITLE
Uhh... Multiplayer...? Multiply!?

### ISSUE THREAD

**Issue by fortyuth** [Daboss7173/Daboss7173.github.io#95]
I have some HUGE questions about the multiplayer capability of Old Prodigy, and want to know...
_UNrelated:_
Does clicking on the VERSION for Definitive Edition redirect to Definitive Edition?
_related:_
How much would servers cost?
How long would it take to implement?

As a broom, I am easily curious.
![Drawing-21 sketchpad](https://github.com/Daboss7173/Daboss7173.github.io/assets/149694059/761988e7-45a1-49d4-936d-006fcadddaec)

**Comment by Daboss7173** [comment]
> I have some HUGE questions about the multiplayer capability of Old Prodigy, and want to know... _UNrelated:_ Does clicking on the VERSION for Definitive Edition redirect to Definitive Edition? _related:_ How much would servers cost? How long would it take to implement?
> 
> As a broom, I am easily curious. ![Drawing-21 sketchpad](https://private-user-images.githubusercontent.com/149694059/289946692-761988e7-45a1-49d4-936d-006fcadddaec.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MTMyNzYsIm5iZiI6MTcwMjQxMjk3NiwicGF0aCI6Ii8xNDk2OTQwNTkvMjg5OTQ2NjkyLTc2MTk4OGU3LTQ1YTEtNDlkNC05MzZkLTAwNmZjYWRkZGFlYy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMjAyOTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWU5ZDMzM2Q2MWJlYjlhNDBkYWFiMjgyNTVkZDM0MjU2MGNhYjFiYWYyN2E5NTcxMDQ2Y2VlZTkzZDU3YjM2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OPvr_3Y9aY8YKk0CqPCmJBAugKoHM8qATz57MG86Z4A)

Clicking on the version for Definitive Edition? Don't know what you mean by that.

As for server cost I don't really know either, I'm probably just gonna use some kind of free cloud service to host the it.

I don't know how long it'll take to add in the multiplayer. It could take a super long time, could be as short as a month. I might have to rewrite a lot of the game's code which could take a while, or maybe not. Time will tell for that one. It could also be never because my budget is really really low, since I'm still pretty young and don't have a job yet.

**Comment by XPMUser** [comment]
I have lots of money, but I don't use my credit card.

**Comment by fortyuth** [comment]
>Clicking on the version for Definitive Edition? Don't know what you mean by that.
I mean that if you click on the version used in Definitive Edition, will it redirect to Definitive Edition?
Also, you could try using some sort of archive to rip the code from an old Prodigy version to get multiplayer, or (I don't know if this would be okay or not) rip the code from Prodigy Reborn.

**Comment by Daboss7173** [comment]
> > Clicking on the version for Definitive Edition? Don't know what you mean by that.
> 
> I mean that if you click on the version used in Definitive Edition, will it redirect to Definitive Edition? Also, you could try using some sort of archive to rip the code from an old Prodigy version to get multiplayer, or (I don't know if this would be okay or not) rip the code from Prodigy Reborn.

You mean 1-50-0? No.

Also, I can only get the client-sided stuff that's in game.min.js. Everything else will need to be rewritten because Prodigy isn't open source.

**Comment by fortyuth** [comment]
I understand, but what about Prodigy Reborn?

**Comment by XPMUser** [comment]
> I understand, but what about Prodigy Reborn?

Prodigy Reborn 1.0 is broken
