### ISSUE TITLE
Earlier than August 2014's Prodigy Versions

### ISSUE THREAD

**Issue by XPMUser** [Daboss7173/Daboss7173.github.io#96]
What would you like to add: 
Earlier than August 2014's Prodigy Versions
How would you want it to be implemented:
Get all the files when you travel to the past.
Any additional context:
Unknown

![OIP](https://github.com/Daboss7173/Daboss7173.github.io/assets/109283781/dedf79cb-cce7-4049-907a-653a737e0b28)

**Comment by XPMUser** [comment]
![R](https://github.com/Daboss7173/Daboss7173.github.io/assets/109283781/ea13b658-c3c8-459b-a07c-731f6d8df56d)
I found an older tutorial.

**Comment by Daboss7173** [comment]
Get all the files when you travel from the past..? What?

You know that's impossible right?
